server:
  port: 7603
spring:
  application:
    name: scwvg-eureka7603
eureka:
  instance:
    hostname: scwvg-eureka7603.com
    instance-id: scwvg-eureka7603
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://scwvg-eureka7601.com:7601/eureka/,http://scwvg-eureka7602.com:7602/eureka/