server:
  port: 7602
spring:
  application:
    name: scwvg-eureka7602
eureka:
  instance:
    hostname:  scwvg-eureka7602.com
    instance-id: scwvg-eureka7602
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://scwvg-eureka7601.com:7601/eureka/,http://scwvg-eureka7603.com:7603/eureka/
