server:
  port: 8007
spring:
  application:
    name: scwvg-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://scwvg-eureka7601.com:7601/eureka/,http://scwvg-eureka7602.com:7602/eureka/,http://scwvg-eureka7603.com:7603/eureka/
  instance:
    instance-id: scwvg-zuul.com
    prefer-ip-address: true
zuul:
  prefix: /wvg            #前缀
  ignored-services: "*"  #屏蔽所有微服务真实名
  routes:
    scwvg.serviceId: scwvg-pmee-consumer   #访问此微服务
    scwvg.path: /**                 #只以前缀访问
